version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
